name: build-gpg
on:
  pull_request:
    branches:
      - master
jobs:
  job-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          java-package: jdk
          architecture: x64
      - id: validate-wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - id: Sign-Documentation
        env:
          RELEASE: true
          IT_GPG_KEY: '${{ secrets.IT_GPG_KEY }}'
          IT_GPG_PASSPHRASE: '${{ secrets.IT_GPG_PASSPHRASE }}'
        run: ./gradlew publishToSonatype closeAndReleaseRepository
